Repository loft-sh/vcluster, pull requests merged in 2024-11, with the labels that each got.

#2262 Upgrades helm and kine
  Dockerfile
  Dockerfile.cli.release
  Dockerfile.release
Labels: backport-to-v0.20

#2270 refactor: add customResources.scope & require scope for fromHost customResources
  chart/tests/clusterrole_test.yaml
  chart/values.schema.json
  config/config.go
  pkg/config/validation.go
Labels: backport-to-v0.21

#2269 fix: removes object cache updates from syncers.
  pkg/controllers/resources/persistentvolumeclaims/syncer.go
  pkg/controllers/resources/pods/ephemeral_containers.go
  pkg/controllers/resources/pods/syncer.go
  pkg/controllers/resources/services/syncer.go
  pkg/controllers/resources/volumesnapshotcontents/syncer.go
  pkg/controllers/resources/volumesnapshots/syncer.go
Labels: backport-to-v0.21

#2259 Exclude rancher managed annotation from ingress sync
  pkg/controllers/resources/ingresses/syncer.go
  pkg/controllers/resources/ingresses/syncer_test.go
  pkg/controllers/resources/ingresses/translate.go
  pkg/controllers/resources/services/syncer.go
Labels: backport-to-v0.20, backport-to-v0.21

#2277 chore: Updated to latest kine version
  Dockerfile
  Dockerfile.release
Labels: backport-to-v0.20, backport-to-v0.21

#2297 bugfix: set correct etcdEndpoints for non embedded etcd based on vcluster config
  chart/templates/etcd-headless-service.yaml
  chart/values.schema.json
  chart/values.yaml
  config/config.go
  config/legacyconfig/migrate.go
  config/values.yaml
  pkg/etcd/client.go
  pkg/k0s/k0s.go
  pkg/k3s/k3s.go
  pkg/k8s/k8s.go
  pkg/setup/initialize.go
Labels: backport-to-v0.20, backport-to-v0.21
