Repository loft-sh/vcluster, pull requests merged in 2024-12, with the labels that each got.

#2310 fix: ignore excluded annotations on create
  pkg/controllers/resources/persistentvolumes/translate.go
  pkg/util/translate/labels.go
  pkg/util/translate/labels_test.go
  pkg/util/translate/translate.go
Labels: backport-to-v0.21

#2309 bugfix(cli): change process of finding specified binary releases
  cmd/vclusterctl/cmd/upgrade.go
  pkg/upgrade/helpers.go
  pkg/upgrade/upgrade.go
  pkg/upgrade/upgrade_test.go
Labels: backport-to-v0.20, backport-to-v0.21

#2335 fix paths in update docs partials workflow
  .github/workflows/sync-config-schema.yaml
Labels: backport-to-v0.22

#2332 Bypass email prompt for upgrades if installed
  cmd/vclusterctl/cmd/platform/destroy.go
  cmd/vclusterctl/cmd/platform/start.go
  pkg/cli/start/start.go
Labels: backport-to-v0.22

#2343 use correct github token env var name, otherwise github cli does not …
  .github/workflows/sync-config-schema.yaml
Labels: backport-to-v0.22

#2329 vcluster config convert statefulSet.affinity bugfix
  config/diff.go
  config/legacyconfig/migrate.go
  config/legacyconfig/migrate_test.go
Labels: backport-to-v0.20, backport-to-v0.21, backport-to-v0.22

#2340 move sleep mode to experimental
  chart/values.schema.json
  config/config.go
Labels: backport-to-v0.22

#2348 Validate comments in config/config.go before generating jsonschema
  .github/workflows/sync-config-schema.yaml
  chart/values.schema.json
  chart/values.yaml
  config/config.go
  hack/schema/main.go
Labels: backport-to-v0.22

#2353 fix: service label sync problems
  pkg/controllers/resources/services/syncer.go
Labels: backport-to-v0.21, backport-to-v0.22
