Repository loft-sh/vcluster, pull requests merged in 2025-02, with the labels that each got.

#2349 bugfix: node allocatable resources correction
  pkg/controllers/resources/nodes/translate.go
Labels: backport-to-v0.19

#2458 Fix typo in error message in client.go
  pkg/platform/client.go
Labels: backport-to-v0.21, backport-to-v0.22

#2449 bugfix(syncer): fix misplaced function parameters in wait.PollUntilContextTimeout function in nodeChanges server filter
  pkg/server/filters/nodechanges.go
Labels: backport-to-v0.21, backport-to-v0.22

#2502 bugfix: objectname validation in from host mappings should be DNSSubd…
  pkg/config/validation.go
  pkg/config/validation_test.go
  test/e2e/syncer/fromhost/configmaps.go
  test/e2e/values.yaml
Labels: backport-to-v0.23

#2503 rename .selector.mappings to .mappings.byName
  chart/templates/clusterrole.yaml
  chart/tests/clusterrole_test.yaml
  chart/values.schema.json
  chart/values.yaml
  config/config.go
  config/values.yaml
  pkg/config/validation.go
  pkg/config/validation_test.go
  pkg/controllers/resources/configmaps/from_host_syncer.go
  pkg/controllers/resources/poddisruptionbudgets/syncer_test.go
  pkg/controllers/resources/secrets/from_host_syncer.go
  test/e2e/values.yaml
Labels: backport-to-v0.23

#2519 fix: probe timeout & apiserver flags
  chart/templates/statefulset.yaml
  pkg/k8s/k8s.go
Labels: backport-to-v0.22, backport-to-v0.23

#2522 fix: service label sync
  pkg/controllers/resources/services/syncer.go
Labels: backport-to-v0.21, backport-to-v0.22, backport-to-v0.23

#2518 Reuse Namespace should be in experimental section
  chart/values.schema.json
  chart/values.yaml
  config/config.go
  config/values.yaml
Labels: backport-to-v0.23

#2528 refactor: cache authorizer & short local k8s timeout
  config/config.go
  pkg/authentication/delegatingauthenticator/delegatingauthenticator.go
  pkg/authorization/delegatingauthorizer/authorizer.go
  pkg/authorization/delegatingauthorizer/cache.go
  pkg/authorization/impersonationauthorizer/authorizer.go
  pkg/authorization/kubeletauthorizer/authorizer.go
  pkg/cli/localkubernetes/configure.go
Labels: backport-to-v0.22, backport-to-v0.23
