Repository loft-sh/vcluster, pull requests merged in 2025-09, with the labels that each got.

#3157 Reapply "fix: patch virtual instead of physical and always add host i…
  pkg/controllers/resources/pods/syncer.go
  pkg/controllers/resources/pods/syncer_test.go
  pkg/controllers/resources/pods/translate/diff.go
  pkg/controllers/resources/pods/translate/translator.go
Labels: backport-to-v0.26, backport-to-v0.27

#3221 refactor: remove target namespace
  .github/workflows/e2e.yaml
  chart/templates/limitrange.yaml
  chart/templates/networkpolicy.yaml
  chart/templates/resourcequota.yaml
  chart/values.schema.json
  chart/values.yaml
  config/config.go
  config/legacyconfig/migrate.go
  config/values.yaml
  pkg/config/config.go
  pkg/controllers/deploy/deploy.go
  pkg/controllers/register.go
  pkg/integrations/metricsserver/metricsserver.go
  pkg/mappings/resources/namespaces.go
  pkg/plugin/plugin.go
  pkg/setup/cleanup_test.go
  pkg/setup/config/config.go
  pkg/setup/controller_context.go
  pkg/util/testing/config.go
  test/README.md
  test/e2e_target_namespace/e2e_target_namespace_test.go
  test/e2e_target_namespace/role.yaml
  test/e2e_target_namespace/targetnamespace/target_namespace.go
  test/e2e_target_namespace/values.yaml
Labels: backport-to-v0.29

#3238 fix: calculate vcluster has correctly
  chart/templates/_vclusterconfighash.tpl
Labels: backport-to-v0.28, backport-to-v0.29
