Repository loft-sh/vcluster, pull requests merged in 2025-04, with the labels that each got.

#2637 fix: update wording in ESO schema
  chart/values.schema.json
  chart/values.yaml
  config/config.go
Labels: backport-to-v0.24

#2647 fix: restart vCluster if k8s exits
  pkg/k8s/k8s.go
Labels: backport-to-v0.21, backport-to-v0.22, backport-to-v0.23, backport-to-v0.24

#2709 fix: using insecure in exportKubeConfig
  pkg/setup/controllers.go
  pkg/setup/controllers_test.go
Labels: backport-to-v0.24

#2712 fix(ci): correctly reference cli-docs workflow trigger in release
  .github/workflows/release.yaml
Labels: backport-to-v0.23, backport-to-v0.24
