Repository loft-sh/vcluster, pull requests merged in 2025-05, with the labels that each got.

#2743 fix(images.txt): Move vcluster-oss to the optional part
  hack/assets/assets.go
Labels: backport-to-v0.25

#2762 refactor: change k8s image logic
  chart/templates/_init-containers.tpl
  chart/tests/statefulset_test.yaml
  config/config_test.go
Labels: backport-to-v0.25

#2764 support multiple wildcards in patch.Translate and patch.Set
  pkg/util/patch/patch.go
  pkg/util/patch/patch_test.go
Labels: backport-to-v0.25

#2766 fix: wrong namespace for platform rbac
  chart/templates/platform-rbac.yaml
  chart/tests/platform-secret-role_test.yaml
Labels: backport-to-v0.23, backport-to-v0.24, backport-to-v0.25

#2770 fix: compaction issue with kine
  pkg/k8s/k8s.go
Labels: backport-to-v0.23, backport-to-v0.24, backport-to-v0.25

#2787 add list & watch permissions for ReferenceGrant
  chart/templates/role.yaml
  chart/tests/role_test.yaml
Labels: backport-to-v0.25

#2774 fix: vCluster connecting with background proxy
  pkg/cli/localkubernetes/configure.go
Labels: backport-to-v0.24, backport-to-v0.25

#2805 Fix compatibility
  config/config.go
  pkg/setup/config.go
Labels: backport-to-v0.24, backport-to-v0.25

#2816 fix: vcluster connect
  pkg/cli/localkubernetes/configure.go
Labels: backport-to-v0.24, backport-to-v0.25

#2834 fix: service cidr detection
  cmd/vcluster/cmd/snapshot.go
  pkg/setup/initialize.go
  pkg/util/servicecidr/servicecidr.go
  pkg/util/servicecidr/servicecidr_test.go
Labels: backport-to-v0.24, backport-to-v0.25
