Repository loft-sh/vcluster, pull requests merged in 2025-01, with the labels that each got.

#2342 bugfix: use correct service-account-issuer in case of custom clusterDomain
  chart/templates/_coredns.tpl
  chart/tests/coredns-configmap_test.yaml
  pkg/k8s/k8s.go
Labels: backport-to-v0.20, backport-to-v0.21, backport-to-v0.22

#2365 fix: exclude import by other vclusters
  pkg/mappings/generic/mapper.go
Labels: backport-to-v0.21, backport-to-v0.22

#2369 Fix coredns
  pkg/setup/controllers.go
Labels: backport-to-v0.22

#2374 fix: create background proxy container
  pkg/cli/localkubernetes/configure.go
Labels: backport-to-v0.21, backport-to-v0.22

#2385 fix: set resource version to 1 on old
  Justfile
  pkg/syncer/syncer.go
Labels: backport-to-v0.21, backport-to-v0.22

#2395 Have container reach host instead of host discover vm IP
  pkg/cli/connect_helm.go
  pkg/cli/localkubernetes/configure.go
  pkg/util/kubeconfig/kubeconfig.go
Labels: backport-to-v0.21, backport-to-v0.22

#2402 fix: storage class sync error
  pkg/controllers/resources/persistentvolumeclaims/syncer.go
  pkg/controllers/resources/persistentvolumes/translate.go
Labels: backport-to-v0.21, backport-to-v0.22

#2406 fix: Only error when we verify they're using a disposable domain.
  pkg/cli/email/validate.go
Labels: backport-to-v0.22

#2416 Fix panic when using exportKubeConfig.name without exportKubeConfig.server
  pkg/setup/controllers.go
Labels: backport-to-v0.21, backport-to-v0.22

#2420 Set fake Node IP for the virtual pod status.HostIP field when ProxyKubelets.ByIP is enabled
  pkg/controllers/resources/pods/syncer.go
  pkg/controllers/resources/pods/syncer_test.go
  pkg/controllers/resources/pods/translate/translator.go
  test/e2e/syncer/pods/pods.go
Labels: backport-to-v0.20, backport-to-v0.21, backport-to-v0.22

#2430 sync spec.Unschedulable field while syncing nodeChanges from virtual to host
  pkg/server/filters/nodechanges.go
Labels: backport-to-v0.21, backport-to-v0.22

#2436 Remove the ServiceBlockDeletion Annotation once the virtual service exists
  pkg/controllers/resources/services/syncer.go
  pkg/controllers/resources/services/translate.go
Labels: backport-to-v0.21, backport-to-v0.22

#2440 fix: fix host to virtual service selector syncing
  pkg/controllers/resources/services/syncer.go
Labels: backport-to-v0.21, backport-to-v0.22

#2437 Remove the ServiceBlockDeletion Annotation once the virtual service exists
  pkg/controllers/resources/services/syncer.go
Labels: backport-to-v0.21, backport-to-v0.22
